Exit scripts on error

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,4 +1,5 @@
-#!/bin/bash -ex
+#!/bin/bash
+set -e # Exit on error
 
 # Retrieve arguments
 domain=$(sudo yunohost app setting letschat domain)
